#!/bin/sh
#
# schema-repo
#
# chkconfig: 345 98 04
# description: Start/Stop schema-repo java service
#
### BEGIN INIT INFO
# Provides: schema-repo
# Required-Start: $local_fs
# Required-Stop: $local_fs
# Default-Start: 3 4 5
# Default-Stop: 0 1 6
# Description: schema-repo
# Short-Description: schema-repo java service
### END INIT INFO

# Source function library.
. /etc/init.d/functions

PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME=schema-repo
DESC=schema-repo
DAEMON=/etc/init.d/${NAME}
USER=kafka
INIT_LOG_DIR=/var/log
PID_FILE=/var/run/${NAME}.pid
JAR_FILE=/usr/local/${NAME}/current/schema-repo-jdbc-bundle.jar
PROPERTIES_FILE=/usr/local/${NAME}/current/config.properties

START_PROG="daemon"
LOCK_FILE=/var/lock/subsys/$NAME

test -x $DAEMON || exit 0
test -x $CONTROL || exit 0

RETVAL=0
set -e

[ -f /etc/default/${NAME} ] && . /etc/default/${NAME}

remove_pid() {
    rm -f $PID_FILE
}

start() {
    set +e
    pgrep -f "java -jar ${JAR_FILE}" > $PID_FILE
    RETVAL=$?
    if [ $RETVAL != 0 ] ; then
       RETVAL=0
       set +e
       su - $USER -c "java -jar ${JAR_FILE} ${PROPERTIES_FILE} &"
       pgrep -f "java -jar ${JAR_FILE}" > $PID_FILE
       set -e

       case "$RETVAL" in
           0)
               if [ -n "$LOCK_FILE" ] ; then
                   touch $LOCK_FILE
               fi
               ;;
           *)
               remove_pid
               RETVAL=1
               ;;
       esac
    fi

    sleep 5
    status
}

stop() {
        set +e
        if [ -f $PID_FILE ]; then
           PID=`cat $PID_FILE`
           kill -HUP $PID
           remove_pid
           if [ -n "$LOCK_FILE" ] ; then
               rm -f $LOCK_FILE
           fi
        else
           echo ${NAME} PID_FILE does not exist
        fi
        sleep 3
        pgrep -f "java -jar ${JAR_FILE}" > /dev/null
        if [ $? = 0 ] ; then
            echo ${NAME} is still running and was NOT stopped
        else
            echo ${NAME} is not running
        fi
        RETVAL=0
}

status() {
    RET=3
    set +e
    pgrep -f "java -jar ${JAR_FILE}" > /dev/null
    RETVAL=$?
    if [ $RETVAL = 0 ] ; then
      echo ${NAME} is running with process ID : `cat $PID_FILE`
      netstat -an|egrep '2876.*LISTEN' > /dev/null
      if [ $? = 0 ] ; then
         echo port 2876 is open and LISTENing for connections...
         RET=0
      else
         echo port 2876 is NOT LISTENing
         RET=4
      fi
    else
      echo ${NAME} server is not running.
      RET=3
    fi
    RETVAL=0
    set -e

    return $RET
}

restart() {
    stop
    start
}

case "$1" in
    start)
        echo -e "Starting $NAME..."
        start
        ;;
    stop)
        echo "Stopping $NAME..."
        stop
        ;;
    status)
        status
        ;;
    restart)
        echo "Restarting $NAME..."
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}" >&2
        RETVAL=1
        ;;
esac

exit $RETVAL
